services:
  prometheus:
    ports:
      - 0.0.0.0:9090:9090
  grafana:
    ports:
      - 0.0.0.0:3000:3000
  metrics:
    ports:
      - 0.0.0.0:8080:8080
  alertmanager:
    ports:
      - 0.0.0.0:9093:9093
