version: '3'

services:
  prometheus:
    image: 'prom/prometheus'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: 'grafana/grafana'

  metrics:
    image: 'mgh/sblab-prometheus'
    depends_on:
      - prometheus
      - grafana

